services:
  - type: web
    name: yt-service
    env: node
    buildCommand: |
      npm install
      curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
      chmod a+rx /usr/local/bin/yt-dlp
      apt-get install -y ffmpeg || true
    startCommand: node server.js
    envVars:
      - key: YT_COOKIE
        sync: false
