services:
  - type: web
    name: yt-service
    env: node
    buildCommand: npm install && pip3 install -U yt-dlp
    startCommand: node server.js
    envVars:
      - key: YT_COOKIE
        sync: false
